### ISSUE TITLE
MarineTraffic Positions 

### ISSUE THREAD

**Issue by JoshuaKrueger** [sea-watch/SAR-Client#176] opened 2017-06-03 11:11 UTC
- [ ] Show all positions of SAR and (visible) Frontex ships (Siem Pilot) on map via MarineTraffic SAT / TER API. 

- [ ] Use this API as a backup for Dongle, EPAK, etc. pp.

**Comment by niczem** [comment] 2017-06-05 10:20
duplicate of #13

**Closed by niczem** 2017-06-05 10:20 UTC
Labels: essential
