### ISSUE TITLE
<Navigation> Leaflets elements in right corner header in map 

### ISSUE THREAD

**Issue by genovefa** [sea-watch/SAR-Client#168] opened 2017-06-02 14:49 UTC
- open page with map
- click on "leafet" ord "sea-watch" link in footer right hand side

Issue:
Linked page opens, User has no possiblility to go back to SAR Client App

Expected:
Either user has a Back Button on each page or somehow a SAR Client home button.

**Comment by niczem** [comment] 2017-06-02 19:57
duplicate of #167

**Closed by niczem** 2017-06-02 19:57 UTC
Labels: bug
